name: Angular Application

on:
  workflow_dispatch:
 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Nodejs-Build:
    uses: azsvcacc/githubaction-workflow/.github/workflows/angular-build.yml@main
    with:
      node-version: "20.x"      # Use a specific Node.js version
      working-directory: "." # Specify the working directory
