name: Angular Application
permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    # runs-on: self-hosted-linux-vm
    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v3

  Nodejs-Build:
    uses: azsvcacc/github-composite-action-repo/.github/workflows/nodejs-build.yml@main
    with:
      node-version: "20.x"      # Use a specific Node.js version
      working-directory: "."    # Specify the working directory
