name: Terraform GCP Deployment

on:
  push:
    branches:
      - Gcp-Terraform-branch
      - main
    paths:
      - terraform/**
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform GCP Plan & Apply
    runs-on: self-hosted-linux-vm
    environment: dev  # GitHub environment name

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Write GCP Credentials to File
        run: |
          echo '${{ secrets.GCP_KEY }}' > ${{ github.workspace }}/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/gcp-key.json" >> $GITHUB_ENV


      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
