name: Build Angular App
  
on:     
  push:
    branches: [ main ]
  workflow_dispatch:
     
jobs:
  build-deploy:
    uses: azsvcacc/github-composite-action-repo/.github/workflows/actions/nodejs@main
    # secrets: inherit
    with:
      nodejsVersion: 18.20.4
