name: Build Angular App

on:     
  push:
    branches: [ main ]
  workflow_dispatch:

jobs: 
  build-deploy:
    runs-on: self-hosted-linux-vm
    steps:
      - name: Build-Nodejs
        uses: azsvcacc/github-composite-action-repo/.github/actions/nodejs@main
        with:
          nodejsVersion: 18.20.4
          github-token: ${{ secrets.GIT_TOKEN }}
      - name: Build Angular app
        run: npm run build
        working-directory: ${{ inputs.working-directory }}
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-artifacts
          path: dist

