name: Build Angular App

on:     
  push:
    branches: [ main ]
  workflow_dispatch:

jobs: 
  build-deploy:
    runs-on: self-hosted-linux-vm
    steps:
      - name: Build-Nodejs
        uses: azsvcacc/github-composite-action-repo/.github/actions/nodejs@main
        with:
          nodejsVersion: 18.20.4
        # secrets: inherit

