name: Built-in variables
 
on:
  workflow_dispatch:
 
jobs:
  job1:
    runs-on: self-hosted-linux-vm

    steps:        
      - name: GitHub
        run: |
          sleep 10
          echo "GITHUB_REF - $GITHUB_REF - ${{ github.ref }}"
          echo "GITHUB_WORKFLOW - $GITHUB_WORKFLOW -  ${{ github.workflow }}"
          echo "GITHUB_RUN_ID - $GITHUB_RUN_ID - ${{ github.run_id }}"
          echo "GITHUB_RUN_NUMBER - $GITHUB_RUN_NUMBER - ${{ github.run_number }}"
          echo "GITHUB_REPOSITORY - $GITHUB_REPOSITORY - ${{ github.repository }}"
          echo "GITHUB_EVENT_NAME - $GITHUB_EVENT_NAME - ${{ github.event_name }}"
          echo "GITHUB_RUN_ATTEMPT - $GITHUB_RUN_ATTEMPT - ${{ github.run_attempt }}"

      - name: Runner
        run: |
         echo "RUNNER_NAME - $RUNNER_NAME - ${{ runner.name }}
         echo "RUNNER_OS - $RUNNER_OS - ${{ runner.os }}
         echo "RUNNER_ARCH - $RUNNER_ARCH - ${{ runner.arch }}
         echo "RUNNER_TEMP - $RUNNER_TEMP - ${{ runner.temp }}
